apiVersion: apps/v1
kind: Deployment
metadata:
  name: important-tool
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      hostIPC: true
      containers:
      - image: busybox
        name: busybox
        resources: {}
